#ifndef _PROFESSION_NPC_H
#define _PROFESSION_NPC_H

#include "Chat.h"
#include "Player.h"
#include "ScriptedGossip.h"
#include "ScriptMgr.h"
#include "SpellMgr.h"
#include <Config.h>

enum AlchemySpells
{
    SPELL_APPRENTICE_ALCHEMY   = 2259,
    SPELL_JOURNEYMAN_ALCHEMY   = 3101,
    SPELL_EXPERT_ALCHEMY       = 3464,
    SPELL_ARTISAN_ALCHEMY      = 11611,
    SPELL_MASTER_ALCHEMY       = 28596,
    SPELL_GRAND_MASTER_ALCHEMY = 51304
};

enum BlacksmithingSpells
{
    SPELL_APPRENTICE_BLACKSMITHING   = 2018,
    SPELL_JOURNEYMAN_BLACKSMITHING   = 3100,
    SPELL_EXPERT_BLACKSMITHING       = 3538,
    SPELL_ARTISAN_BLACKSMITHING      = 9785,
    SPELL_MASTER_BLACKSMITHING       = 29844,
    SPELL_GRAND_MASTER_BLACKSMITHING = 51300
};

enum EnchantingSpells
{
    SPELL_APPRENTICE_ENCHANTING   = 7411,
    SPELL_JOURNEYMAN_ENCHANTING   = 7412,
    SPELL_EXPERT_ENCHANTING       = 7413,
    SPELL_ARTISAN_ENCHANTING      = 13920,
    SPELL_MASTER_ENCHANTING       = 28029,
    SPELL_GRAND_MASTER_ENCHANTING = 51313
};

enum EngineeringSpells
{
    SPELL_APPRENTICE_ENGINEERING   = 4036,
    SPELL_JOURNEYMAN_ENGINEERING   = 4037,
    SPELL_EXPERT_ENGINEERING       = 4038,
    SPELL_ARTISAN_ENGINEERING      = 12656,
    SPELL_MASTER_ENGINEERING       = 30350,
    SPELL_GRAND_MASTER_ENGINEERING = 51306
};

enum InscriptionSpells
{
    SPELL_APPRENTICE_INSCRIPTION   = 45357,
    SPELL_JOURNEYMAN_INSCRIPTION   = 45358,
    SPELL_EXPERT_INSCRIPTION       = 45359,
    SPELL_ARTISAN_INSCRIPTION      = 45360,
    SPELL_MASTER_INSCRIPTION       = 45361,
    SPELL_GRAND_MASTER_INSCRIPTION = 45363
};

enum JewelcraftingSpells
{
    SPELL_APPRENTICE_JEWELCRAFTING   = 25229,
    SPELL_JOURNEYMAN_JEWELCRAFTING   = 25230,
    SPELL_EXPERT_JEWELCRAFTING       = 28894,
    SPELL_ARTISAN_JEWELCRAFTING      = 28895,
    SPELL_MASTER_JEWELCRAFTING       = 28897,
    SPELL_GRAND_MASTER_JEWELCRAFTING = 51311
};

enum LeatherworkingSpells
{
    SPELL_APPRENTICE_LEATHERWORKING   = 2108,
    SPELL_JOURNEYMAN_LEATHERWORKING   = 3104,
    SPELL_EXPERT_LEATHERWORKING       = 3811,
    SPELL_ARTISAN_LEATHERWORKING      = 10662,
    SPELL_MASTER_LEATHERWORKING       = 32549,
    SPELL_GRAND_MASTER_LEATHERWORKING = 51302
};

enum TailoringSpells
{
    SPELL_APPRENTICE_TAILORING   = 3908,
    SPELL_JOURNEYMAN_TAILORING   = 3909,
    SPELL_EXPERT_TAILORING       = 3910,
    SPELL_ARTISAN_TAILORING      = 12180,
    SPELL_MASTER_TAILORING       = 26790,
    SPELL_GRAND_MASTER_TAILORING = 51309
};

enum CookingSpells
{
    SPELL_APPRENTICE_COOKING   = 2550,
    SPELL_JOURNEYMAN_COOKING   = 3102,
    SPELL_EXPERT_COOKING       = 3413,
    SPELL_ARTISAN_COOKING      = 18260,
    SPELL_MASTER_COOKING       = 33359,
    SPELL_GRAND_MASTER_COOKING = 51296
};

enum FirstAidSpells
{
    SPELL_APPRENTICE_FIRST_AID   = 3273,
    SPELL_JOURNEYMAN_FIRST_AID   = 3274,
    SPELL_EXPERT_FIRST_AID       = 7924,
    SPELL_ARTISAN_FIRST_AID      = 10846,
    SPELL_MASTER_FIRST_AID       = 27028,
    SPELL_GRAND_MASTER_FIRST_AID = 45542
};

enum FishingSpells
{
    SPELL_APPRENTICE_FISHING   = 7620,
    SPELL_JOURNEYMAN_FISHING   = 7731,
    SPELL_EXPERT_FISHING       = 7732,
    SPELL_ARTISAN_FISHING      = 18248,
    SPELL_MASTER_FISHING       = 33095,
    SPELL_GRAND_MASTER_FISHING = 51294,
    SPELL_APPRENTICE_FISHING_DUPLICATE = 62734
};

enum MiningSpells
{
    SPELL_APPRENTICE_MINING   = 2575,
    SPELL_JOURNEYMAN_MINING   = 2576,
    SPELL_EXPERT_MINING       = 3564,
    SPELL_ARTISAN_MINING      = 10248,
    SPELL_MASTER_MINING       = 29354,
    SPELL_GRAND_MASTER_MINING = 50310
};

enum SkinningSpells
{
    SPELL_APPRENTICE_SKINNING   = 8613,
    SPELL_JOURNEYMAN_SKINNING   = 8617,
    SPELL_EXPERT_SKINNING       = 8618,
    SPELL_ARTISAN_SKINNING      = 10768,
    SPELL_MASTER_SKINNING       = 32678,
    SPELL_GRAND_MASTER_SKINNING = 50305
};

enum HerbalismSpells
{
    SPELL_APPRENTICE_HERBALISM   = 2366,
    SPELL_JOURNEYMAN_HERBALISM   = 2368,
    SPELL_EXPERT_HERBALISM       = 3570,
    SPELL_ARTISAN_HERBALISM      = 11993,
    SPELL_MASTER_HERBALISM       = 28695,
    SPELL_GRAND_MASTER_HERBALISM = 50300
};

#endif